- name: hostgroup searchhead tasks
  hosts: searchhead
  tasks:
  - name: set serverName in server.conf and host in inputs.conf
    become: true
    become_user: ec2-user
    shell: |
      if [ -f "/opt/splunk/etc/system/local/inputs.conf" ] 
      then
        echo "/opt/splunk/etc/system/local/inputs.conf does exist."
      else    
        cat <<EOF >>/opt/splunk/etc/system/local/inputs.conf
        [default]
        host = GOEL-searchhead
        EOF
      fi  

      if [ -f "/opt/splunk/etc/system/local/server.conf" ] 
      then
        echo "/opt/splunk/etc/system/local/server.conf does exist."
      else    
        cat <<EOF >>/opt/splunk/etc/system/local/server.conf
        [general]
        serverName = GOEL-searchhead
        EOF
      fi   